name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: bazel run //src/java/com/claro/examples/calculator_example:push_calculator_compiler_image --incompatible_restrict_string_escapes=false
