name: Push to Docker Hub

on:
  push:
    branches: [ main ]

jobs:

  Build-and-Push:

    runs-on: ubuntu-latest

    steps:
      - 
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and Push the Calculator Compiler Docker Image
        # --incompatible_restrict_string_escapes=false because there's a bug in 
        # https://github.com/bazelbuild/rules_docker/blob/7da0de3d094aae5601c45ae0855b64fb2771cd72/container/push.bzl#L34
        # where they're using an invalid escape sequence "\{". Instead of filing a bug on them I'm just working around it...
        run: bazel run //src/java/com/claro:push_calculator_compiler_image --incompatible_restrict_string_escapes=false
